### ISSUE TITLE
Issue with since when attempting to filter with hours (--since)

### ISSUE THREAD

**Issue by AhmetcanFR** [achyuthjoism/tweeds#1]
When you type `tweeds -s "node" --since  "2022-12-30" --json file.json` it works perfectly.

But adding the time to the --since parameter  like this : `tweeds -s "node" --since  "2022-12-30 12:00:00" --json file.json` Nothing is given(0 Results).

I believe there is an issue with the hours condition.

**Comment by jois-code** [comment]
working on it 😊

**Comment by Ramizworking** [comment]
> working on it 😊

Do you use discord boss ?

**Comment by jois-code** [comment]
> When you type `tweeds -s "node" --since "2022-12-30" --json file.json` it works perfectly.
> 
> But adding the time to the --since parameter like this : `tweeds -s "node" --since "2022-12-30 12:00:00" --json file.json` Nothing is given(0 Results).
> 
> I believe there is an issue with the hours condition.

We can't use hour condition in this module,
But if you want to use this "hour condition" you can use this python module,
https://github.com/tweepy/tweepy (requires API key 🔑)

Thank You,
Achyuth
