### ISSUE TITLE
Order not found

### ISSUE THREAD

**Issue by Wolfie96xd** [achyuthjoism/tweeds#3]
┌──(kali㉿kali)-[~]
└─$ tweeds --help
tweeds: Order not found

**Comment by jois-code** [comment]
I checked it on google cloud shell, it is working.
![Screenshot 2023-04-14 at 10 30 07 PM](https://user-images.githubusercontent.com/67776857/232110096-bc10c95d-0dd5-4fe1-8ac0-47a2a504de33.png)
